//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryChecking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryChecking()
        {
            this.InventoryCheckingDetails = new HashSet<InventoryCheckingDetail>();
        }
    
        public int ID { get; set; }
        public int StoreID { get; set; }
        public System.DateTime CheckinDate { get; set; }
        public int Creator { get; set; }
        public int Status { get; set; }
    
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryCheckingDetail> InventoryCheckingDetails { get; set; }
    }
}
