//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string PicUrl { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
