//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportOrder()
        {
            this.TransportOrderDetails = new HashSet<TransportOrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SrcStoreID { get; set; }
        public Nullable<int> DesStoreID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public int Type { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportOrderDetail> TransportOrderDetails { get; set; }
    }
}
