//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrderDetail
    {
        public int ID { get; set; }
        public int TransportOrderID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TransportOrder TransportOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
