//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInventoryCheckingDetailService : SkyWeb.DatVM.Data.IBaseService<InventoryCheckingDetail>
    {
    }
    
    public partial class InventoryCheckingDetailService : SkyWeb.DatVM.Data.BaseService<InventoryCheckingDetail>, IInventoryCheckingDetailService
    {
        public InventoryCheckingDetailService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInventoryCheckingDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
