//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ISupplierService : SkyWeb.DatVM.Data.IBaseService<Supplier>
    {
    }
    
    public partial class SupplierService : SkyWeb.DatVM.Data.BaseService<Supplier>, ISupplierService
    {
        public SupplierService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ISupplierRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
