//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ITransportOrderDetailService : SkyWeb.DatVM.Data.IBaseService<TransportOrderDetail>
    {
    }
    
    public partial class TransportOrderDetailService : SkyWeb.DatVM.Data.BaseService<TransportOrderDetail>, ITransportOrderDetailService
    {
        public TransportOrderDetailService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ITransportOrderDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
