//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Employee>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int Roles { get; set; }
    			public virtual decimal Salary { get; set; }
    			public virtual Nullable<System.DateTime> DateOfBirth { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual int StoreID { get; set; }
    	
    	public EmployeeViewModel() : base() { }
    	public EmployeeViewModel(HmsService.Models.Entities.Employee entity) : base(entity) { }
    
    }
}
