//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingDetailViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.InventoryCheckingDetail>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int CheckingID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual int Quantity { get; set; }
    			public virtual decimal Price { get; set; }
    			public virtual int Status { get; set; }
    	
    	public InventoryCheckingDetailViewModel() : base() { }
    	public InventoryCheckingDetailViewModel(HmsService.Models.Entities.InventoryCheckingDetail entity) : base(entity) { }
    
    }
}
