//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.OrderDetail>
    {
    	
    			public virtual int OrderID { get; set; }
    			public virtual int ProductID { get; set; }
    			public virtual int Quantity { get; set; }
    			public virtual decimal Amount { get; set; }
    	
    	public OrderDetailViewModel() : base() { }
    	public OrderDetailViewModel(HmsService.Models.Entities.OrderDetail entity) : base(entity) { }
    
    }
}
