//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Order>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int EmployeeID { get; set; }
    			public virtual int PaymentID { get; set; }
    			public virtual int CustomerID { get; set; }
    			public virtual System.DateTime Date { get; set; }
    			public virtual int StoreID { get; set; }
    			public virtual int Status { get; set; }
    	
    	public OrderViewModel() : base() { }
    	public OrderViewModel(HmsService.Models.Entities.Order entity) : base(entity) { }
    
    }
}
