//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Payment>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int ToOrderID { get; set; }
    			public virtual int Type { get; set; }
    			public virtual decimal Amount { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int ToOrderID { get; set; }
    	
    	public PaymentViewModel() : base() { }
    	public PaymentViewModel(HmsService.Models.Entities.Payment entity) : base(entity) { }
    
    }
}
