//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.ProductImage>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual Nullable<int> ProductId { get; set; }
    			public virtual string PicUrl { get; set; }
    			public virtual Nullable<int> DisplayOrder { get; set; }
    	
    	public ProductImageViewModel() : base() { }
    	public ProductImageViewModel(HmsService.Models.Entities.ProductImage entity) : base(entity) { }
    
    }
}
