//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategoryViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.ProductCategory>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string Name { get; set; }
    	
    	public ProductCategoryViewModel() : base() { }
    	public ProductCategoryViewModel(HmsService.Models.Entities.ProductCategory entity) : base(entity) { }
    
    }
}
