//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Supplier>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string ContactPerson { get; set; }
    			public virtual string Phone { get; set; }
    			public virtual string Fax { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public SupplierViewModel() : base() { }
    	public SupplierViewModel(HmsService.Models.Entities.Supplier entity) : base(entity) { }
    
    }
}
