//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportOrderViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.TransportOrder>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual Nullable<int> SrcStoreID { get; set; }
    			public virtual Nullable<int> DesStoreID { get; set; }
    			public virtual Nullable<int> SupplierID { get; set; }
    			public virtual Nullable<System.DateTime> DepartDate { get; set; }
    			public virtual Nullable<System.DateTime> ArrivalDate { get; set; }
    			public virtual int Type { get; set; }
    	
    	public TransportOrderViewModel() : base() { }
    	public TransportOrderViewModel(HmsService.Models.Entities.TransportOrder entity) : base(entity) { }
    
    }
}
